### ISSUE TITLE
Would you consider a compiled release?

### ISSUE THREAD

**Issue by Gavin-Holt** [daviddrysdale/mdbook-footnote#4]
Hi

We are looking to use mdBook at our Hospital. Footnotes are important for referencing, and are broken in the current release of mdBook (https://github.com/rust-lang/mdBook/issues/2169) since Aug23.

I am not keen to try and set up rust, just to add some features to mdBook - my IT department will have a fit!

If your preprocessor still works, would you consider making a compiled release for windows (compatible with [mdbook-v0.4.36-x86_64-pc-windows-msvc.zip](https://github.com/rust-lang/mdBook/releases/download/v0.4.36/mdbook-v0.4.36-x86_64-pc-windows-msvc.zip))

If you have escaped windows, and don't have a compiled version to hand - sorry to bother you.

Kind Regards Gavin Holt

**Comment by daviddrysdale** [comment]
Sorry, that would involve setting up a new workflow and I don't have a Windows machine to test anything on anyway.

Good luck, though.

**Comment by mick2025s** [comment]
Hello @Gavin-Holt !

Here is solution I'm using on Windows11:

You can utilize Docker to build and integrate the `mdbook-footnote` preprocessor. Here's how:

1. **Set Up Your Project Directory**:
   - Ensure the following structure:
     ```
     project_root/
     ├── docker-compose.yml
     ├── Dockerfile.footnote
     ├── bin/
     ├── src/
     │   ├── SUMMARY.md
     │   ├── chapter_1.md
     │   └── chapter_2.md
     └── book.toml
     ```

2. **Create `docker-compose.yml`**:
   This file defines two services: one to build the `mdbook-footnote` binary and another to build the book with footnote support.
```yaml
version: '3.8'

services:
  mdbook-footnote-builder2:
    build:
      context: .
      dockerfile: Dockerfile.footnote
    container_name: mdbook_footnote_builder2
    entrypoint: ["/bin/sh", "-c"]
    command: ["cp /usr/local/bin/mdbook-footnote /book/mdbook-footnote"] 
    volumes:
      - ./bin:/book

  mdbook-pdf:
    image: hollowman6/mdbook-pdf
    container_name: mdbook_pdf_builder
    working_dir: /book
    volumes:
      - ./:/book    
      - ./bin/mdbook-footnote:/usr/local/bin/mdbook-footnote
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        mdbook clean &&
        mdbook build
```

3. **Create `Dockerfile.footnote`**:
   This Dockerfile builds the `mdbook-footnote` binary using Rust.
```dockerfile
# Use Rust official image to build the binary
FROM rust:latest AS builder

# Install mdbook-footnote
RUN cargo install mdbook-footnote --root /usr/local

# Final image with only the compiled binary
FROM alpine:latest

# Copy the compiled binary from the builder stage
COPY --from=builder /usr/local/bin/mdbook-footnote /usr/local/bin/mdbook-footnote

# Set the default entrypoint
ENTRYPOINT ["/usr/local/bin/mdbook-footnote"]

```

4. **Build the `mdbook-footnote` Binary**:
   Run the following command to build and extract the `mdbook-footnote` binary:
```sh
docker-compose up --build mdbook-footnote-builder2
   ```

5. **Verify the Binary**:
   Ensure the binary is created in the `./bin` directory:
```sh
ls ./bin
   ```

6. **Build the Book with Footnote Support**:
   Start the `mdbook-builder` service to compile your Markdown files with footnote support:
```sh
docker-compose up --build mdbook-pdf
   ```

This will compile your markdown to PDF using footnotes.
Output file will be in: `/book/pdf/` directory.

Script output:
```bash
[+] Running 1/1
 ✔ Container mdbook_pdf_builder  Created                                                                                                           
0.0s Attaching to mdbook_pdf_builder
mdbook_pdf_builder  | 2025-02-20 08:17:46 [INFO] (mdbook::book): Book building has started
mdbook_pdf_builder  | Warning: The footnote-preprocessor plugin was built against version 0.4.45 of mdbook, but we're being called from version 0.4.43
mdbook_pdf_builder  | 2025-02-20 08:17:46 [INFO] (mdbook::book): Running the html backend
mdbook_pdf_builder  | Warning: The footnote-preprocessor plugin was built against version 0.4.45 of mdbook, but we're being called from version 0.4.43
mdbook_pdf_builder  | 2025-02-20 08:17:46 [INFO] (mdbook::book): Running the pdf backend
mdbook_pdf_builder  | 2025-02-20 08:17:46 [INFO] (mdbook::renderer): Invoking the "pdf" renderer
mdbook_pdf_builder  | Generating PDF, please be patient...
mdbook_pdf_builder  | PDF successfully generated at: /book/book/pdf/output.pdf
mdbook_pdf_builder  | Warning: The footnote-preprocessor plugin was built against version 0.4.45 of mdbook, but we're being called from version 0.4.43
mdbook_pdf_builder  | 2025-02-20 08:17:51 [INFO] (mdbook::book): Running the pdf-outline backend
mdbook_pdf_builder  | 2025-02-20 08:17:51 [INFO] (mdbook::renderer): Invoking the "pdf-outline" renderer
mdbook_pdf_builder exited with code 0
```
